version: '3.4'

services:
  prover:
    build:
      dockerfile: ./Dockerfile.prover
    image: prover:latest
    restart: unless-stopped
    # ports:
    #   - "6060:6060"
    command: >
      ./prover_server
    environment:
      - L1_RPC=${L1_RPC}
      - L2_RPC=${L2_RPC}
      - COINBASE="0xfabb0ac9d68b0b445fb7357272ff202c5651694a"
      - SCROLL_PROVER_ASSETS_DIR=./configs
      - GENERATE_EVM_VERIFIER=false
    volumes:
      - ./configs:/configs
      - ./prove_params:/prove_params
      - ./proof:/proof
  
  challenge-handler:
    depends_on:
        prover:
          condition: service_started
    build:
      dockerfile: ./Dockerfile.handler
    image: challenge-handler:latest
    restart: unless-stopped
    # ports:
    #   - "6071:6060"
    command: >
      ./challenge-handler
    environment:
      - L1_RPC=${L1_RPC}
      - L2_RPC=${L2_RPC}
      - PROVER_RPC=prover:3030
      - L1_ROLLUP=${L1_ROLLUP}
      - L1_ROLLUP_PRIVATE_KEY=${L1_ROLLUP_PRIVATE_KEY}

  # Only used in test scene.
  challenger:
    depends_on:
        challenge-handler:
          condition: service_started
    build:
      dockerfile: ./Dockerfile.challenger
    image: challenger:latest
    restart: unless-stopped
    command: >
      ./auto_challenge
    environment:
      - INTERVAL=12
      - L1_RPC=${L1_RPC}
      - L1_ROLLUP=${L1_ROLLUP}
      - CHALLENGER_PRIVATEKEY=${CHALLENGER_PRIVATEKEY}
