version: '3.4'

volumes:
  sequencer_geth_data:
  sequencer_node_data:

services:
  sequencer_geth:
    image: morphism-geth:latest
    ports:
      - "6688:8545"
    healthcheck:
      test: curl -f http://localhost:6688
      interval: 30s
      timeout: 5s
      retries: 3
    volumes:
      - "sequencer_geth_data:${GETH_DATA_DIR}"
      - "${PWD}/jwt-secret.txt:${JWT_SECRET_PATH}"
      - "${PWD}/genesis_geth.json:${GENESIS_FILE_PATH}"
    entrypoint: # pass the L2 specific flags by overriding the entry-point and adding extra arguments
      - "/bin/bash"
      - "/entrypoint.sh"

  sequencer_node:
    depends_on:
      sequencer_geth:
        condition: service_started
    image: morphism-node:latest
    ports:
      - "26666:26656"
    environment:
      - EMPTY_BLOCK_DELAY=true
      - MORPH_NODE_L2_ETH_RPC=http://sequencer_geth:8545
      - MORPH_NODE_L2_ENGINE_RPC=http://sequencer_geth:8551
      - MORPH_NODE_L2_ENGINE_AUTH=jwt-secret.txt
      ## todo need to replace it to a public network
      - MORPH_NODE_L1_ETH_RPC=${L1_ETH_RPC}
      - MORPH_NODE_SYNC_DEPOSIT_CONTRACT_ADDRESS=0x6900000000000000000000000000000000000001
      ## - MORPH_NODE_SYNC_START_HEIGHT=88854536
    volumes:
      - "sequencer_node_data:${NODE_DATA_DIR}"
      - "${PWD}/jwt-secret.txt:${JWT_SECRET_PATH}"
    command: >
      morphnode
      --dev-sequencer
      --home $NODE_DATA_DIR
